package mx.uacj.juego_ra.ui.controladores

import kotlinx.serialization.Serializable

@Serializable
object OpcionNavegacionPantallaPrincipal

@Serializable
object OpcionNavegacionPantallaPistaInformacion

@Serializable
object PantallaInteraccionIncorrecta

@Serializable
object PantallaInteraccionCorrecta

@Serializable
object OpcionNavegacionPantallaPistaInteractuable

@Serializable
object  OpcionNavegacionPantallaPistaAgitable

@Serializable
object OpcionNavegacionPantallaPistaCamara